# a minimal Nginx container including containerbuddy and a simple virtulhost config
FROM autopilotpattern/nginx:branch-48-nginx_connections_unhandled_total-appears-incorrect

# Add our configuration files
COPY etc /etc
